
spring:
  #datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bubble?useSSL=true&charset=utf8&serverTimezone=GMT
    username: Stony
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      properties:
        transport:
          tcp:
            connect_timeout: 120s

  # redis
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  mapperLocations: classpath:com/zjmeow/bboard/dao/*.xml
  typeAliasesPackage: com.zjmeow/bboard/model/po
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    context-path: /v1


